---
title: "Time Series Analysis Final Project: Dynamic Regression Models"
author: "Julie Xu & Karyn Nguyen"

date: "March 6, 2020"
output:
  html_document: default
  header-includes: \usepackage{color}
fontsize: 12pt
margin: 1in
---
<!--
-->

```{r setup, echo=FALSE, message=F, warning=F, include=FALSE}
#install.packages("fpp2")
library(fpp2)

rm(list = ls())  # Clear the working space

setwd("/Users/karynnguyenMBP/Desktop/Econ 174")
getwd()

```

```{r graphs1, echo=FALSE, message=F, warning=F, include=TRUE}

airfaredata = read.csv("CPIAIRLINES.csv", sep=",", header=TRUE) #Data for airfare
airrate = ts(airfaredata$CUSR0000SETG0, start = 1989, frequency = 12) #Declare data as time series 

autoplot(airrate) + ylab("Consumer Price Index for Airfare of US Consumers") + xlab("Year") + ggtitle("Consumer Price Index of Airfares for All Urban Consumers: 1989-2020")

#Time Series Regression 
linear = tslm(airrate ~ trend) 
fit1 = fitted(linear)  
res1 = residuals(linear)
autoplot(airrate) + autolayer(fit1) + autolayer(res1) + ylab("Consumer Price Index for Airfare of US Consumers") + xlab("Year") + ggtitle("Consumer Price Index of Airfares for All Urban Consumers: 1989-2020")
checkresiduals(res1)

#Exponential Smoothing
fit = ets(airrate, damped=TRUE)
summary(fit)
autoplot(forecast(fit, h=124)) + ylab("Consumer Price Index for Airfare of US Consumers") + xlab("Year") 

#ARIMA Model 
fit2 = auto.arima(airrate, stepwise=FALSE, approximation=FALSE)
autoplot(forecast(fit2, h=124)) + ylab("Consumer Price Index for Airfare of US Consumers") + xlab("Year") 
checkresiduals(fit2)

#Dynamic Regression Model
inflationdata = read.csv("Inflation.csv", sep=",", header=TRUE) #Data for inflation
inflationrate = ts(inflationdata$Inflation, start = 1989, frequency = 12) #Declaring data as time series 

fit = auto.arima(airrate, xreg=inflationrate)
fcast = forecast(fit, xreg=rep(mean(inflationrate),12), h=12)
autoplot(fcast) + xlab("Year") + ylab("Change in Consumer Price Index")

```
&nbsp;
